apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: agricultural-cockroach-go 
  janus-idp.io/tekton: agricultural-cockroach-go
  backstage.io/kubernetes-id: agricultural-cockroach-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: agricultural-cockroach-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  