apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: agricultural-cockroach-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: agricultural-cockroach-go 
  name: agricultural-cockroach-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: agricultural-cockroach-go
    weight: 100 
